export const projects = [
   {
      id: '1',
      title: 'Github Jobs Finder',
      tags: 'frontend, api, design',
      description: `This is a service that helps you find a job all over the world!
      It uses the github jobs API. You can see a lot of vacancies and
      apply for them.`,
      imgPath: '/images/github-jobs.webp',
      filterKeys: 'frontend,all',
      tech: ['React', 'Next.js', 'Github API'],
      githubLink: 'https://github.com/rooohaa/github-jobs-app',
      date: 'April 2021',
      demoLink: 'https://github-jobs-app-two.vercel.app/',
   },
   {
      id: '2',
      title: 'Task Manager',
      tags: 'fullstack, json api, data visualization',
      description:
         'Task manager with JSON server that helps user to manage his tasks. This is web-application with CRUD operations and Data visualization.',
      imgPath: '/images/todo-app.webp',
      filterKeys: 'fullstack,all,frontend',
      tech: ['React', 'TypeScript', 'JSON Server'],
      githubLink: 'https://github.com/rooohaa/jetbrains-todo-app',
      date: 'March 2021',
   },
   {
      id: '3',
      title: 'Netflix clone',
      tags: 'frontend, api, firebase',
      description:
         'Netflix clone written with Vue.js + Firebase. It uses TMDB API for fetching movies. You can register, view new movies and add them to your list.',
      imgPath: '/images/netflix.jpeg',
      filterKeys: 'frontend,all,fullstack',
      tech: ['Vue', 'Firebase', 'Tmdb API'],
      githubLink: 'https://github.com/rooohaa/netflix-clone',
      date: 'January 2021',
      demoLink: 'https://netflixx-clonee.netlify.app/',
   },
   {
      id: '4',
      title: 'Restaurant Finder',
      tags: 'fullstack, pern',
      description:
         'Pet project for learning fullstack development with PERN stack. I have learned working with database on backend, creating REST API. Frontend built with SSR Next.js + React',
      imgPath: '/images/pern.jpeg',
      filterKeys: 'all,fullstack',
      tech: [
         'React',
         'TypeScript',
         'Express.js',
         'Node.js',
         'PostgreSQL',
         'Redux',
         'Next.js',
      ],
      githubLink: 'https://github.com/rooohaa/restaurant-finder',
      date: 'June 2021',
   },
   {
      id: '5',
      title: 'Trello Mini Clone',
      tags: 'frontend, vanilla js',
      description:
         'Frontend challenge to learn drag and drop functionality. Great trello mini clone for managing task with drag-drop api.',
      imgPath: '/images/trello.jpeg',
      filterKeys: 'all,frontend',
      tech: ['HTML5', 'CSS3', 'JavaScript'],
      githubLink: 'https://github.com/rooohaa/trello-mini-clone',
      date: 'June 2021',
      demoLink: 'https://trello-min-clone.netlify.app/',
   },
   {
      id: '6',
      title: 'Sneaker Store Layout',
      tags: 'frontend, layout, design',
      description:
         'Responsive, well designed layout for Sneaker Store website. It has 5 pages and interactive elements like slider, popup, etc.',
      imgPath: '/images/sneaker.webp',
      filterKeys: 'layout,all,frontend',
      tech: ['HTML5', 'CSS3', 'JavaScript', 'SASS'],
      githubLink: 'https://github.com/rooohaa/sneaker-store-dev',
      date: 'December 2020',
      demoLink: 'https://sneaker-store.netlify.app/',
   },
   {
      id: '7',
      title: 'Corporate website',
      tags: 'frontend, design',
      description:
         'This is my first team development. I have been working on the client side of a website. Acquainted with the framework Next.js.',
      imgPath: '/images/human-rights.webp',
      filterKeys: 'all,frontend,commercial',
      tech: ['Next.js', 'React', 'TypeScript', 'Redux'],
      githubLink: 'https://bitbucket.org/avex_team/nghrdc-frontend/src/master/',
      date: 'May 2021',
      demoLink: 'https://nghrdc.kz/',
   },
   {
      id: '8',
      title: 'Football players review',
      tags: 'fullstack, data visualization',
      description:
         'Fullstack project for my DBMS course. It uses large dataset which is being manipulated on frontend with CRUD and Data visualization.',
      imgPath: '/images/football.jpeg',
      filterKeys: 'all,frontend,fullstack',
      tech: [
         'React',
         'TypeScript',
         'Node.js',
         'Express.js',
         'Oracle',
         'Chart.js',
      ],
      githubLink: 'https://github.com/rooohaa/dbms-project',
      date: 'April 2021',
   },
];
